# ASSIGNMENT 4

## Q1) Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
a) Addition of 2 in all the element

b) Multiply 3 with all the elements

c) Divide every element by 2

In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a+2)
print(a*3)
print(a/2)
    

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


## Q2) Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

b) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [12]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])[::-1]
print("Reversed array=",arr)

# i. x array
x = np.array([1,2,3,4,5,1,2,1,1,1])
count= {}
for num in x:
    if num in count:
        count[num] += 1
    else:
        count[num] = 1
        
freq = max(count, key=count.get)
indexes_x = [i for i, val in enumerate(x) if val == freq]

print("Most frequent value in x:", freq)
print("Indices of the most frequent value in x:", indexes_x)

# ii. y array
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
count_y = {}
for num in y:
    if num in count_y:
        count_y[num] += 1
    else:
        count_y[num] = 1
max_freq = max(count_y.values())
most_frequent_y = [key for key, value in count_y.items() if value == max_freq]
indices_y = {}
for val in most_frequent_y:
    indices_y[val] = [i for i, elem in enumerate(y) if elem == val]
print("Most frequent values in y:", most_frequent_y)
print("Indices of the most frequent values in y:")
for val, indices in indices_y.items():
    print(f"Value {val}: {indices}")


Reversed array= [5 4 6 3 2 1]
Most frequent value in x: 1
Indices of the most frequent value in x: [0, 5, 7, 8, 9]
Most frequent values in y: [1, 3]
Indices of the most frequent values in y:
Value 1: [0, 1, 2]
Value 3: [4, 8, 9]


## Q3) For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:

a) Access 1st row, 2nd column

b) Access 3rd row, 1st column

In [13]:
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
a = arr[0, 1]  
print("1st row, 2nd column element:", a)
b = arr[2, 0]
print("3rd row, 1st column element:", b)


1st row, 2nd column element: 20
3rd row, 1st column element: 70


## Q4) Write program to create an 1-D NumPy array named (Your Name) with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,shape, total elements, the data type of each element and total number of bytes consumedby the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [17]:
import numpy as np
mannya = np.linspace(10, 100, 25)
print("Array:", mannya)
print("Dimensions of the array:", mannya.ndim)
print("Shape of the array:", mannya.shape)
print("Total elements in the array:", mannya.size)
print("Data type of each element:", mannya.dtype)
print("Total bytes consumed by the array:", mannya.nbytes)
transpose_array = mannya.reshape(-1, 1)
print("Transposed Array using reshape():\n", transpose_array)
transposed_with_T = mannya.T
print("Transposed Array using T attribute:\n", transposed_with_T)


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of the array: 1
Shape of the array: (25,)
Total elements in the array: 25
Data type of each element: float64
Total bytes consumed by the array: 200
Transposed Array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed Array using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


## Q5) Create a 2-D Array of three rows and four columns, named ucs420_(your_name) with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_(your_name). Resize the array to two rows and three columns and name it as resized_ ucs420_(your_name).

In [19]:
import numpy as np
ucs420_mannya = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])
mean_array = np.mean(ucs420_mannya)
median_array = np.median(ucs420_mannya)
max_array = np.max(ucs420_mannya)
min_array = np.min(ucs420_mannya)
unique_elements = np.unique(ucs420_mannya)
print("Mean:", mean_array)
print("Median:", median_array)
print("Max:", max_array)
print("Min:", min_array)
print("Unique elements:", unique_elements)
reshaped_ucs420_mannya = ucs420_mannya.reshape(4, 3)
print("Reshaped to 4x3:\n", reshaped_ucs420_mannya)
ucs420_mannya_resized = np.resize(ucs420_mannya, (2, 3))
print("Resized to 2x3:\n", ucs420_mannya_resized)


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped to 4x3:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized to 2x3:
 [[10 20 30]
 [40 50 60]]
